name: zstv
on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest  
    
    steps:
    
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: writexml
      run: |
        python3 ./aa.py
    - name: Commit
      run: |
        git config --global user.email wxjwolf@gmail.com
        git config --global user.name wxjwolf
        git add zs.xml
        git commit -m "舟山电信itv"
        #git pull --rebase
        git push -u origin "master"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
